#!/usr/bin/env zsh

function title() {
  echo ""
  echo "==================================================================="
  echo "  $1"
  echo "==================================================================="
}

SOURCE_DIR="sync"
DEST_DIR="$HOME"

FETCH="true"
SOURCE="false"
if [[ "$@" =~ "--no-fetch" ]]; then FETCH="false"; fi
if [[ "$@" =~ "--source" ]]; then SOURCE="true"; fi

if [[ "$FETCH" == "true" ]]; then
  title "Saving list of autocomplete gh repos"
  if ! command -v gh &> /dev/null
  then
      title "SKIPPING: gh not installed"
  else
    PROJECTS_FILE="$SOURCE_DIR/.oh-my-zsh/custom/plugins/projects/data.txt"
    true > $PROJECTS_FILE
    QUERIES=(${(s/,/)PROJECTS_REMOTE})
    for q in "${QUERIES[@]}"; do
      echo "$q"
      gh ls-repos-name "$q" >> $PROJECTS_FILE
    done
  fi

  title "zsh-autosuggestions"
  if ! command -v gh &> /dev/null
  then
      title "SKIPPING: gh not installed"
  else
    PLUGIN_DIR="$SOURCE_DIR/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
    if [ -d "$PLUGIN_DIR" ]; then
      cd $PLUGIN_DIR
      gh repo sync
      cd -
    else
      gh repo clone zsh-users/zsh-autosuggestions $PLUGIN_DIR
    fi
  fi
fi

title "rsync all files starting with a dot"
rsync -ahvI --exclude ".DS_Store" --exclude ".git/" $SOURCE_DIR/.* $DEST_DIR

title "expand \$DEST_DIR in gh config"
sed -i '' "s|\$HOME|$DEST_DIR|g" $DEST_DIR/.config/gh/config.yml
echo "done"

title "rsync git files individually"
for file in sync/git*(.); do
  echo "- file: $file"
  rsync -ahvI --ignore-times --no-R --no-implied-dirs $file "$DEST_DIR/.$(basename -- $file)"
  echo ""
done

title "set global npm configs"
if ! command -v npm &> /dev/null
then
    title "SKIPPING: npm not installed"
else
  IFS=$'\n'
  for i in $(cat < sync/npmrc); do
    echo "- npm: $i"
    npm config set "$i"
  done
fi

if [[ "$SOURCE" == "true" ]]; then
  title "sourcing profile and rc"
  source $DEST_DIR/.zprofile
  source $DEST_DIR/.zshrc
fi

title "all done!"
