#!/usr/bin/env zsh

SYNC_DIR="sync"
FETCH="$1"

function title() {
  echo ""
  echo "==================================================================="
  echo "  $1"
  echo "==================================================================="
}

if [[ $FETCH != "--no-fetch" ]]; then
  title "Saving list of autocomplete gh repos"
  if ! command -v gh &> /dev/null
  then
      title "SKIPPING: gh not installed"
  else
    PROJECTS_FILE="$SYNC_DIR/.oh-my-zsh/custom/plugins/projects/data.txt"
    true > $PROJECTS_FILE
    QUERIES=(${(s/,/)PROJECTS_REMOTE})
    for q in "${QUERIES[@]}"; do
      echo "$q"
      gh ls-repos-name "$q" >> $PROJECTS_FILE
    done
  fi

  title "zsh-autosuggestions"
  if ! command -v gh &> /dev/null
  then
      title "SKIPPING: gh not installed"
  else
    PLUGIN_DIR="$SYNC_DIR/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
    if [ -d "$PLUGIN_DIR" ]; then
      cd $PLUGIN_DIR
      gh repo sync
      cd -
    else
      gh repo clone zsh-users/zsh-autosuggestions $PLUGIN_DIR
    fi
  fi
fi

title "rsync all files starting with a dot"
rsync -ahvI --exclude ".DS_Store" --exclude ".git/" $SYNC_DIR/.* $HOME

title "expand \$HOME in gh config"
sed -i '' "s|\$HOME|$HOME|g" $HOME/.config/gh/config.yml
echo "done"

title "rsync git files individually"
for file in sync/git*(.); do
  echo "- file: $file"
  rsync -ahvI --ignore-times --no-R --no-implied-dirs $file "$HOME/.$(basename -- $file)"
  echo ""
done

title "set global npm configs"
if ! command -v npm &> /dev/null
then
    title "SKIPPING: npm not installed"
else
  IFS=$'\n'
  for i in $(cat < sync/npmrc); do
    echo "- npm: $i"
    npm config set "$i"
  done
fi

title "all done!"
