tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/services"
brew "act"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "arduino-cli"
brew "atuin"
brew "python@3.11"
brew "awscli"
brew "bat"
brew "boost"
brew "glib"
brew "cairo"
brew "chezmoi"
brew "coreutils"
brew "direnv"
brew "folly"
brew "edencommon"
brew "exa"
brew "exiftool"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "fd"
brew "harfbuzz"
brew "leptonica"
brew "libarchive"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "findutils"
brew "fnm"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "go"
brew "pkg-config"
brew "gobject-introspection"
brew "grep"
brew "handbrake"
brew "hdf5"
brew "hyperfine"
brew "libheif"
brew "imagemagick"
brew "jpeg"
brew "jq"
brew "librsvg"
brew "mas"
brew "media-info"
brew "qt"
brew "mkvtoolnix"
brew "moreutils"
brew "mozjpeg"
brew "mp4v2"
brew "vapoursynth"
brew "yt-dlp"
brew "mpv"
brew "nghttp2"
brew "ngrep"
brew "openblas"
brew "opusfile"
brew "p7zip"
brew "poppler"
brew "postgresql@14", restart_service: true
brew "python@3.9"
brew "rename"
brew "ripgrep"
brew "rustup-init"
brew "sox"
brew "ssh-copy-id"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "vips"
brew "volta"
brew "watchman"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
cask "1password"
cask "1password-cli"
cask "airfoil"
cask "apparency"
cask "appzapper"
cask "bartender"
cask "bose-updater"
cask "choosy"
cask "db-browser-for-sqlite"
cask "discord"
cask "docker"
cask "firefox"
cask "flux"
cask "font-ubuntu-mono-nerd-font"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "keepingyouawake"
cask "logitech-options"
cask "makemkv"
cask "microsoft-teams"
cask "min"
cask "obsidian"
cask "pgadmin4"
cask "postico"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "raspberry-pi-imager"
cask "raycast"
cask "runjs"
cask "slack"
cask "sonos"
cask "superduper"
cask "suspicious-package"
cask "tailscale"
cask "transmission"
cask "twitch-studio"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Drafts", id: 1435957248
mas "Due", id: 524373870
mas "Duplicate Photos Fixer Pro", id: 963642514
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "GPX Editor", id: 924782627
mas "GPX Viewer", id: 920631838
mas "Homecoming for Mastodon", id: 1666139593
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Noir", id: 1592917505
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Photomator", id: 1444636541
mas "Soro", id: 1550457805
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Tweaks for Twitter", id: 1567751529
mas "Userscripts-Mac-App", id: 1463298887
mas "Xcode", id: 497799835
vscode "aytee17.vscode-oceanic-next-sublime"
vscode "bierner.markdown-preview-github-styles"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dracula-theme.theme-dracula"
vscode "earshinov.permute-lines"
vscode "esbenp.prettier-vscode"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "GraphQL.vscode-graphql"
vscode "GraphQL.vscode-graphql-execution"
vscode "GraphQL.vscode-graphql-syntax"
vscode "idleberg.applescript"
vscode "jinliming2.vscode-go-template"
vscode "Meezilla.json"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.vscode-serial-monitor"
vscode "naumovs.theme-oceanicnext"
vscode "Prisma.prisma"
vscode "ronnidc.nunjucks"
vscode "sharat.vscode-brewfile"
vscode "silvenon.mdx"
vscode "SimonSiefke.svg-preview"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "toba.vsfire"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "unifiedjs.vscode-mdx"
vscode "wmaurer.change-case"
