[onepassword]
  # This uses 1Password as the SSH agent. It is configurable because it doesn't work
  # with all SSH clients since it uses public keys as the IdentifyFile. See this list
  # at the link for which clients it works with:
  # https://developer.1password.com/docs/ssh/agent/advanced/#match-key-with-host
  ssh = true

[onepassword.personal]
  vault = "5chnupnoo6zc5bijsqv6upxa5e"
  account = "lukekarrys.1password.com"
