version: "1"
git_protocol: ssh
prompt: enabled
aliases:
    prvw: "!gh pr view --web"
    wd: "!gh repo view --web --branch $(git branch --show-current)"
    co: pr checkout
    ls-repos-name: |-
        api graphql -F search='$1 archived:false' -f query='query ($search: String!) {
          search (query: $search, type: REPOSITORY, first: 100) {
            nodes {
              ... on Repository {
                name
              }
            }
          }
        }' --jq '.data.search.nodes[].name'
    nwo: repo view --json nameWithOwner --jq .nameWithOwner
    run-id: '!gh run list -w "$1" -L 1 --json databaseId -q ".[].databaseId"'
    pr-release: |-
        !gh pr view "$@" $(gh pr list --search='label:"autorelease: tagged","autorelease: pending"' --state=all -L 1 --json number -q ".[].number")
