#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

var DEFAULT_LINTER = 'jshint';
var POSSIBLE_LINTERS = ['eslint', 'jshint', 'standard'];
var RC_NAME = '.sublimelinterrc';

var rcPath = path.join(process.cwd(), RC_NAME);
var enableLinter = process.argv.slice(2)[0] || DEFAULT_LINTER;

var config = { linters: {} };
POSSIBLE_LINTERS.forEach(function (linter) {
  config.linters[linter] = { '@disable': true };
});

try {
  config.linters[enableLinter]['@disable'] = false;
} catch (e) {
  throw new Error('Could not set linter: ' + enableLinter);
}

fs.writeFile(rcPath, JSON.stringify(config, null, 2), function (err) {
  if (err) {
    throw err;
  } else {
    console.log('ENABLED:', enableLinter, rcPath);
  }
});
