tap "adoptopenjdk/openjdk"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "glib"
brew "coreutils"
brew "exiftool"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "pkg-config"
brew "grep"
brew "handbrake"
brew "highlight"
brew "httrack"
brew "hub"
brew "libtool"
brew "imagemagick"
brew "jq"
brew "mas"
brew "media-info"
brew "mkvtoolnix"
brew "moreutils"
brew "mp4v2"
brew "youtube-dl"
brew "mpv"
brew "ngrep"
brew "opencv@2"
brew "p7zip"
brew "python@2"
brew "python@3.9"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rename"
brew "sox"
brew "ssh-copy-id", link: true
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "vips"
brew "watchman"
brew "wget"
brew "zsh"
brew "zsh-completions"
cask "1password"
cask "adoptopenjdk8"
cask "airfoil"
cask "alfred"
cask "anylist"
cask "appzapper"
cask "bartender"
cask "bose-updater"
cask "calibre"
cask "choosy"
cask "doxie"
cask "dropbox"
cask "firefox"
cask "fluid"
cask "flux"
cask "focus"
cask "garmin-express"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "kap"
cask "keepingyouawake"
cask "logitech-options"
cask "makemkv"
cask "min"
cask "mono-mdk"
cask "ngrok"
cask "postgres"
cask "postico"
cask "qlcolorcode"
cask "qlstephen"
cask "quicklook-json"
cask "rocket"
cask "skype"
cask "spotify"
cask "sqlitebrowser"
cask "superduper"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Divvy", id: 413857545
mas "Drafts", id: 1435957248
mas "Due", id: 524373870
mas "Duplicate Photos Fixer Pro", id: 963642514
mas "EasyRes", id: 688211836
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "GoldenHour", id: 1506521630
mas "GPX Editor", id: 924782627
mas "GPX Viewer", id: 920631838
mas "iMovie", id: 408981434
mas "Instapaper Save", id: 1481302432
mas "Keynote", id: 409183694
mas "Monodraw", id: 920404675
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
