tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
brew 'boost'
brew 'coreutils'
brew 'exiftool'
brew 'lame'
brew 'git'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'findutils'
brew 'libpng'
brew 'freetype'
brew 'gdbm'
brew 'jpeg'
brew 'libtiff'
brew 'libtool'
brew 'xz'
brew 'imagemagick'
brew 'gifify'
brew 'lua'
brew 'highlight'
brew 'hub'
brew 'mas'
brew 'moreutils'
brew 'ngrep'
brew 'openssl'
brew 'pcre'
brew 'readline'
brew 'postgresql', restart_service: true
brew 'redis'
brew 'rename'
brew 'trash'
brew 'tree'
brew 'vim', args: ['with-override-system-vi']
brew 'watchman'
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'homebrew/dupes/grep'
cask '1password'
cask 'aerial'
cask 'airfoil'
cask 'alfred'
cask 'appzapper'
cask 'backblaze'
cask 'bartender'
cask 'betterzipql'
cask 'calibre'
cask 'cloudup'
cask 'dropbox'
cask 'dupeguru'
cask 'firefox'
cask 'fluid'
cask 'flux'
cask 'focus'
cask 'google-chrome'
cask 'id3-editor'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
cask 'keepingyouawake'
cask 'lastfm'
cask 'openemu'
cask 'postico'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rocket'
cask 'spotify'
cask 'sublime-text'
cask 'superduper'
cask 'xld'
mas 'Xcode', id: 497799835
mas 'Keynote', id: 409183694
mas 'iMovie', id: 408981434
mas 'Fantastical 2', id: 975937182
mas 'Letterpress', id: 1070543522
mas 'HyperDock', id: 449830122
mas 'Day One', id: 1055511498
mas 'iA Writer', id: 775737590
mas 'Due', id: 524373870
mas 'Slack', id: 803453959
mas 'Duplicate Photos Fixer Pro', id: 963642514
mas 'Pages', id: 409201541
mas 'GarageBand', id: 682658836
mas 'Divvy', id: 413857545
mas 'Monodraw', id: 920404675
mas 'DaisyDisk', id: 411643860
mas 'Numbers', id: 409203825
