# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# some characters to copy paste
# ╭
# ╰
# ╮
# ╯
# ─
# 
# 
# ❯

format = '[╭──](dimmed purple) $all$fill$custom$battery$time [─╮](dimmed purple)$line_break$character'
right_format = "[╯](dimmed purple)"

[package]
symbol = '󰏓'
format = '[$symbol $version]($style) '
version_format = '${raw}'
style = 'dimmed 208'
display_private = true

[line_break]
disabled = false

[status]
disabled = false
symbol = ""
format = '[$symbol]($style) '

[git_status]
style = 'dimmed yellow'

[nodejs]
disabled = true

[fill]
symbol = "─"
style = "dimmed purple"

[character]
error_symbol = "[╰─❯](dimmed purple)"
success_symbol = "[╰─❯](dimmed purple)"

[cmd_duration]
min_time = 50
show_milliseconds = true
format = '[$duration](dimmed yellow) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
truncation_length = 20
truncation_symbol = "…"

# Right Prompt
# All formats use a leading space

[battery]
format = ' [$symbol$percentage]($style)'

[[battery.display]]
threshold = 20
style = 'dimmed red'

[[battery.display]]
threshold = 50
style = 'dimmed yellow'

[[battery.display]]
threshold = 98
style = 'dimmed green'

[time]
disabled = false
time_format = '%-l:%M'
format = ' [$time]($style)'
use_12hr = true
style = 'dimmed purple'

# get the current npm version in a fast way, only works with fnm
[custom.npm]
# jq is a few ms slower
# command = "jq -r .version $(realpath $(which node) | sed 's|/bin/node|/lib/node_modules/npm/package.json|')"
command = "grep -m 1 '\"version\"' $(realpath $(which node) | sed 's|/bin/node|/lib/node_modules/npm/package.json|') | sed -n 's/.*\"version\": \"\\([^\"]*\\)\",/\\1/p'"
style = 'dimmed red'
symbol = ""
format = " [$symbol $output]($style)"
detect_extensions =	['js', 'mjs', 'cjs', 'ts', 'mts', 'cts']
detect_files = ['package.json', '.node-version', '.nvmrc']	
detect_folders = ['node_modules']
shell = ['sh']

# 9ms vs 23ms for the builtin nodejs section which runs node --version
# only works with fnm
[custom.node]
command = "realpath $(which node) | sed -n 's|.*/node-versions/v\\([^/]*\\)/.*|\\1|p'"
style = 'dimmed green'
symbol = ""
format = " [$symbol $output]($style)"
detect_extensions =	['js', 'mjs', 'cjs', 'ts', 'mts', 'cts']
detect_files = ['package.json', '.node-version', '.nvmrc']	
detect_folders = ['node_modules']
shell = ['sh']
